apiVersion: apps/v1
kind: Deployment
metadata:
  name: asa-performance-tests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asa-performance-tests
  template:
    metadata:
      labels:
        app: asa-performance-tests
    spec:
      containers:
        - name: asa-performance-tests
          image: asa-performance-tests:tag