apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: argocd-test
  labels:
    app: argocd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-test
  template:
    metadata:
      labels:
        app: argocd-test
    spec:
      containers:
        - name: argocd-test
          image: joaonunes96/argocd-test:1.0
          ports:
            - containerPort: 8080