apiVersion: batch/v1
kind: Job
metadata:
  name: deployment
  namespace: argocd-test
  labels:
    app: argocd-test
spec:
  parallelism: 3
  completions: 3
  template:
    spec:
      containers:
        - name: argocd-test
          image: joaonunes96/argocd-test4:1.0
          command:
            - java
            - -jar
            - asa-performance-tests-0.0.1-SNAPSHOT-jar-with-dependencies.jar
          args:
            - -rate=10
            - -producers=10
            - -duration=$(DURATION_VAR)
            - -brand=pp
          env:
            - name: DURATION_VAR
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['argocd.argoproj.io/duration']
          ports:
            - containerPort: 8080