apiVersion: batch/v1
kind: Job
metadata:
  name: deployment
  namespace: argocd-test
  labels:
    app: argocd-test
spec:
  ttlSecondsAfterFinished: 10
  parallelism: 3
  completions: 3
  template:
    metadata:
      labels:
        app: argocd-test
    spec:
      restartPolicy: Never
      containers:
        - name: argocd-test
          image: joaonunes96/argocd-test4:1.0
          command: ["java", "-jar", "asa-performance-tests-0.0.1-SNAPSHOT-jar-with-dependencies.jar", "-rate=100", "-producers=10", "-duration=12", "-brand=pp", "JAVA_PID=$!","kill -SIGINT $JAVA_PID" ]
          ports:
            - containerPort: 8080